Repository InfinityFlowApp/keycloak-event-listener-temporal, pull requests merged in 2024-04, with the labels that each got.

#26 Add MTLS Auth Support
  .devcontainer/devcontainer.json
  README.md
  pom.xml
  src/main/kotlin/app/infinityflow/keycloak/events/TemporalEventListenerProviderFactory.kt
  src/test/kotlin/app/infinityflow/keycloak/events/tests/TestScope.kt
Labels: maintenance

#28 Automate artifact publishing to maven central
  .github/workflows/release.yml
  pom.xml
  settings.xml
Labels: github_actions, maintenance

#31 Add categories security & dependencies to Release drafter
  .github/release-drafter.yml
Labels: maintenance

#32 Upload release artifacts on publish job step
  .github/workflows/release.yml
Labels: maintenance

#38 Allow authority override with different mTLS domain
  README.md
  src/main/kotlin/app/infinityflow/keycloak/events/TemporalEventListenerProviderFactory.kt
  src/test/kotlin/app/infinityflow/keycloak/events/tests/TestScope.kt
Labels: enhancement, minor

#36 Preempt PR builds on new push
  .github/workflows/release-drafter.yml
Labels: maintenance
